---
title: "Drug_sensitivity_analysis"
author: "Jiang Li"
output: html_document
date: "2024-05-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Drug sensitivity analysis
```{r}
ctrp.sample.info<-data.table::fread('CTRP/Cell_line_annotation_ctrp.txt',data.table = F)
ctrp.sample.info<-ctrp.sample.info[ctrp.sample.info$OncoTree1=='Ovary',]
cell.line<-intersect(ctrp.sample.info$Name, colnames(ctrp.expr)) %>% intersect(colnames(ctrp.drug))
ctrp.drug<-ctrp.drug[,cell.line]
ctrp.expr<-ctrp.expr[,cell.line]
ctrp.drug<-ctrp.drug[apply(ctrp.drug,1,function(x){sum(is.na(x)) < (length(cell.line)*0.5)}),]
ctrp.drug<-impute::impute.knn(ctrp.drug %>% as.matrix())[['data']] %>% as.data.frame()
ctrp.drug<- (1-ctrp.drug/30)

drug.gene.df<-expand.grid(rownames(ctrp.expr), rownames(ctrp.drug)) %>% as.data.frame()
colnames(drug.gene.df)<-c('gene','drug')
drug.gene.df$anova.p<-NA
drug.gene.df$auc<-NA
drug.gene.df$gene <- as.character(drug.gene.df$gene)
drug.gene.df$drug <- as.character(drug.gene.df$drug)


for(i in 1:nrow(drug.gene.df)){
  df<-data.frame(
    gene=ctrp.expr[drug.gene.df$gene[i],] %>% unlist(),
    drug=ctrp.drug[drug.gene.df$drug[i],] %>% unlist()
  )
  drug.gene.df$anova.p[i]<-anova(lm(drug~gene, df))[1,5]
  drug.gene.df$auc[i]<-pROC::roc(
    ifelse(df$drug > median(df$drug),1,0),
    df$gene,quiet=T,direction='<'
  )$auc
}
rm(i,df)

lapply(genes[c(5)], function(x){
  df<-drug.gene.df[drug.gene.df$gene == x,] %>% left_join(drug.info[,c('ID','CLINICAL.STATUS')],by=c('drug'='ID'))
  ggplot(df,aes(x=auc,y=-log10(anova.p)))+geom_point(aes(color=I(ifelse((auc >= 0.7 | auc <= 0.3) & anova.p < 0.05, 'red','lightgrey'))))+
    theme_classic()+labs(x='AUC',y='ANOVA -log10 (P-value)',title=x)+
    geom_hline(yintercept = -log10(0.05),lty='dashed',color='lightgrey')+
    geom_vline(xintercept = c(0.3,0.7),lty='dashed',color='lightgrey')+
   ggrepel::geom_label_repel(aes(label=ifelse((auc >= 0.7 | auc <= 0.3) & anova.p < 0.05, drug,'')),label.size = NA,max.overlaps=Inf)+
    theme(
      legend.position = 'none',
      axis.text= element_text(size=15,family ="sans"),
      axis.title= element_text(size = 15,family ="sans")
    )
}) %>% cowplot::plot_grid(plotlist = ., nrow=1)
```

